"""Do police records count the same women again and again? Repeat victims in Los Angeles, 2020 to 2023.

Police records count reports; the survey counts people (and caps one person's repeated victimizations at 10). LAPD's
pre-NIBRS records (the Los-Angeles-CA-Assault-Victim-Rates-by-Race-and-Sex-2020-2023 project's eda_data.csv and eda_data_deadly.csv: simple and aggravated assault, codes
624, 626, 230 and 236) carry the victim's age, sex and descent and the block address, but no person identifier.

A repeat is approximated: two reports at the same block address involving women of the same descent whose birth
years (incident year minus age) are within 1 of each other. Block addresses are shared by many residents, so some of
these are different women. A placebo measures that: matches at the same address and descent with birth years 5 to 7
apart (on either side, the same width of window), which are almost all different people. The excess of true-window
over placebo-window matches estimates real repeats.

For each group: reports, the share with a same-woman match, the placebo share, and an estimate of distinct women,
records minus the merges the matching makes, scaled by the share of matches that are not chance. Then the ratio of
Black to White (and Hispanic) women counted as women rather than reports, as a multiplier on the ratio of reports.
Women 18 and older, descent known, address a numbered block. Reports without a usable address cannot be matched and
count as one woman each, so repeats are understated.

  python scripts/la_repeat_victims.py      ->  out/la_repeat_victims.json, out/la_repeat_victims.md
"""
import json
import pathlib

import numpy as np
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
LA = ROOT.parent / "Los-Angeles-CA-Assault-Victim-Rates-by-Race-and-Sex-2020-2023"
GROUPS = {"B": "Black", "W": "White", "H": "Hispanic", "A": "Asian"}


def load():
    d = pd.concat([pd.read_csv(LA / f"data/{f}", dtype=str) for f in ("eda_data.csv", "eda_data_deadly.csv")], ignore_index=True)
    d = d.drop_duplicates("div_record")
    d["age"] = pd.to_numeric(d["vict_age"], errors="coerce")
    d = d[(d["vict_sex"] == "F") & d["vict_race"].isin(GROUPS) & (d["age"] >= 18)].copy()
    d["loc"] = d["location"].fillna("").str.split().str.join(" ")
    d["usable"] = d["loc"].str.match(r"^\d")
    d["by"] = d["year_incident_date"].astype(int) - d["age"].astype(int)
    return d


def matches(g, lo, hi):
    """For each record in one (address, descent) group: is there another record with birth-year difference in [lo, hi]?"""
    by = g["by"].to_numpy()
    diff = by[None, :] - by[:, None]
    np.fill_diagonal(diff, 10_000)
    return ((diff >= lo) & (diff <= hi)).any(axis=1)


def persons(by):
    """Distinct women in one group by chaining birth years within 1 of the cluster's first."""
    by = np.sort(by)
    n, start = 0, None
    for b in by:
        if start is None or b - start > 1:
            n, start = n + 1, b
    return n


def main():
    d = load()
    u = d[d["usable"]]
    rows = {}
    for code, name in GROUPS.items():
        x = u[u["vict_race"] == code]
        true_m, plac_m, merged = 0, 0, 0
        for _, g in x.groupby("loc"):
            if len(g) < 2:
                continue
            true_m += matches(g, -1, 1).sum()
            plac_m += (matches(g, 5, 7).sum() + matches(g, -7, -5).sum()) / 2
            merged += len(g) - persons(g["by"].to_numpy())
        n_all = int((d["vict_race"] == code).sum())
        real = max(0.0, 1 - plac_m / true_m) if true_m else 0.0
        women = n_all - merged * real
        rows[name] = {"reports": n_all, "with_usable_address": int(len(x)), "share_true_match": round(true_m / len(x) * 100, 1),
                      "share_placebo_match": round(plac_m / len(x) * 100, 1), "share_of_matches_real": round(real * 100, 1),
                      "merged_reports": int(merged), "est_women": int(round(women)), "reports_per_woman": round(n_all / women, 3)}
    mult = {g: round((rows["Black"]["est_women"] / rows["Black"]["reports"]) / (rows[g]["est_women"] / rows[g]["reports"]), 3) for g in ("White", "Hispanic", "Asian")}
    page = json.loads((LA / "data/page_data.json").read_text())["rates"]
    recorded = {g: round(page["Black"]["F"] / page[g]["F"], 2) for g in ("White", "Hispanic", "Asian")}
    res = {"groups": rows, "multiplier_on_ratio": mult, "ratio_reports_la_page": recorded,
           "ratio_women_implied": {g: round(recorded[g] * mult[g], 2) for g in mult}}
    (ROOT / "out/la_repeat_victims.json").write_text(json.dumps(res, indent=1) + "\n")
    L = ["# Los Angeles: repeat victims, 2020 to 2023", "",
         "Women 18 and older, simple and aggravated assault, LAPD pre-NIBRS records. A repeat: same block address, same descent, birth years within 1. "
         "Placebo: birth years 5 to 7 apart. Generated by `scripts/la_repeat_victims.py`.", "",
         "| Group | Reports | With a usable address | Same-woman match % | Placebo match % | Matches that are real % | Estimated women | Reports per woman |",
         "|---|---|---|---|---|---|---|---|"]
    for g, r in rows.items():
        L.append(f"| {g} | {r['reports']:,} | {r['with_usable_address']:,} | {r['share_true_match']} | {r['share_placebo_match']} | {r['share_of_matches_real']} | {r['est_women']:,} | {r['reports_per_woman']} |")
    L += ["", "| Black women's ratio | Counting reports (LA page, all ages) | Multiplier, counting women | Counting women |", "|---|---|---|---|"]
    for g in mult:
        L.append(f"| vs {g} | {recorded[g]}x | {mult[g]} | {res['ratio_women_implied'][g]}x |")
    (ROOT / "out/la_repeat_victims.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
