"""Emergency department visits for assault by race and sex, from the 2022 NHAMCS public-use file.

The National Hospital Ambulatory Medical Care Survey samples emergency department visits nationally; its records do
not depend on anyone calling the police. A visit is an assault visit when any listed cause of injury or diagnosis
carries an ICD-10-CM code X92 to Y09, the definition in NCHS Data Brief 481. Rates: visit weights (PATWT) over ACS
2020 to 2024 residents (Census Reporter, data/nhamcs/acs_us.json), per 100,000 a year, for adults 18 and older by
race and ethnicity (RACERETH: 1 non-Hispanic White, 2 non-Hispanic Black, 3 Hispanic) and sex (SEX: 1 female, 2
male), and for everyone. Intervals: 95%, treating the sampled visits as Poisson counts and ignoring the survey
design, so they understate the true uncertainty; the cells are small (a few dozen visits each).

Data: data/nhamcs/ed2022-stata.dta, the Stata version of the 2022 ED file from CDC's FTP (fetched through the
Internet Archive, since the FTP stalled); the documentation is wb_doc22.txt beside it.

  python scripts/nhamcs_ed.py      ->  out/nhamcs_ed.json, out/nhamcs_ed.md
"""
import json
import pathlib
import re

import numpy as np
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
D = ROOT / "data/nhamcs"
RACE = {1: ("White", "B01001H"), 2: ("Black", "B01001B"), 3: ("Hispanic", "B01001I")}
SEX = {1: "women", 2: "men"}


def assault_code(s):
    m = re.match(r"^([XY])(\d\d)", str(s).upper().replace(".", ""))
    if not m:
        return False
    letter, n = m.group(1), int(m.group(2))
    return (letter == "X" and n >= 92) or (letter == "Y" and n <= 9)


def main():
    d = pd.read_stata(D / "ed2022-stata.dta", convert_categoricals=False)
    cols = [c for c in d.columns if re.match(r"(CAUSE|DIAG)\d$", c)]
    d["assault"] = pd.concat([d[c].map(assault_code) for c in cols], axis=1).any(axis=1)
    pop = json.loads((D / "acs_us.json").read_text())["data"]["01000US"]
    adults = {"women": lambda t: sum(float(pop[t]["estimate"][f"{t}{i:03d}"]) for i in range(22, 32)),
              "men": lambda t: sum(float(pop[t]["estimate"][f"{t}{i:03d}"]) for i in range(7, 17))}
    cells = {}
    for r, (name, t) in RACE.items():
        for s, sex in SEX.items():
            x = d[(d["RACERETH"] == r) & (d["SEX"] == s) & (d["AGE"] >= 18) & d["assault"]]
            p = adults[sex](t)
            cells[f"{name} {sex}"] = {"sampled_visits": int(len(x)), "weighted_visits": int(round(x["PATWT"].sum())), "residents_18plus": int(round(p)),
                                      "rate_per_100k": round(x["PATWT"].sum() / p * 1e5)}
        x = d[(d["RACERETH"] == r) & d["assault"]]
        p = float(pop[t]["estimate"][t + "001"])
        cells[f"{name}, all ages and both sexes"] = {"sampled_visits": int(len(x)), "weighted_visits": int(round(x["PATWT"].sum())), "residents": int(round(p)),
                                                   "rate_per_100k": round(x["PATWT"].sum() / p * 1e5)}

    def ratio(a, b):
        ra, rb = cells[a], cells[b]
        if not ra["sampled_visits"] or not rb["sampled_visits"]:
            return None
        q = ra["rate_per_100k"] / rb["rate_per_100k"]
        se = np.sqrt(1 / ra["sampled_visits"] + 1 / rb["sampled_visits"])  # Poisson, design ignored
        return {"ratio": round(q, 2), "ci95": [round(q * np.exp(-1.96 * se), 2), round(q * np.exp(1.96 * se), 2)]}

    ratios = {"Black women vs White women": ratio("Black women", "White women"), "Black women vs Hispanic women": ratio("Black women", "Hispanic women"),
              "Black men vs White men": ratio("Black men", "White men"),
              "Black vs White, all ages and both sexes": ratio("Black, all ages and both sexes", "White, all ages and both sexes")}
    res = {"year": 2022, "assault_visits_sampled": int(d["assault"].sum()), "assault_visits_weighted": int(round(d.loc[d["assault"], "PATWT"].sum())), "cells": cells, "ratios": ratios}
    (ROOT / "out/nhamcs_ed.json").write_text(json.dumps(res, indent=1) + "\n")
    L = ["# Emergency department visits for assault by race and sex, NHAMCS 2022", "",
         f"{res['assault_visits_sampled']} sampled visits with an assault code (X92 to Y09), weighted to {res['assault_visits_weighted']:,} visits. "
         "Rates per 100,000 residents a year; adults 18 and older unless noted. Intervals ignore the survey design. Generated by `scripts/nhamcs_ed.py`.", "",
         "| Group | Sampled visits | Weighted visits | Rate per 100,000 |", "|---|---|---|---|"]
    for k, c in cells.items():
        L.append(f"| {k} | {c['sampled_visits']} | {c['weighted_visits']:,} | {c['rate_per_100k']:,} |")
    L += ["", "| Ratio | Value | 95% interval |", "|---|---|---|"]
    for k, v in ratios.items():
        L.append(f"| {k} | {v['ratio'] if v else 'n/a'} | {v['ci95'][0]} to {v['ci95'][1]} |" if v else f"| {k} | n/a | |")
    (ROOT / "out/nhamcs_ed.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
