"""New York: Black women's recorded assault rate against White women's, by where the assault happened and which police
recorded it, 2022 to 2025. Women of all ages, NYPD complaints (felony assault and assault 3 and related), per 100,000
women residents of the group (ACS, the national run's cache). Hispanic first. Public housing is the premises type
"RESIDENCE - PUBLIC HOUSING" (the complaint file's housing-development field is not null-coded, so it cannot be used).

  python scripts/nyc_premises.py      ->  out/nyc_premises.json, out/nyc_premises.md   (after data/nyc/complaints_women_premises.csv)
"""
import json
import pathlib

import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUN = ROOT.parent / "US-Large-Cities-Assault-Victim-Rates-by-Race-and-Sex-2022-2025"
RACE = {"BLACK": "Black", "WHITE": "White", "WHITE HISPANIC": "Hispanic", "BLACK HISPANIC": "Hispanic", "ASIAN / PACIFIC ISLANDER": "Asian"}
YEARS = 4


def main():
    d = pd.read_csv(ROOT / "data/nyc/complaints_women_premises.csv", dtype=str)
    d["n"] = d["n"].astype(int)
    d["g"] = d["vic_race"].map(RACE)
    d = d.dropna(subset=["g"])
    popF = {g: v["F"] for g, v in json.loads((RUN / "cities/new_york/out/population.json").read_text())["city"].items()}
    tot = d.groupby("g")["n"].sum()
    res = d.groupby("prem_typ_desc")["n"].sum()
    residences = [p for p in d["prem_typ_desc"].dropna().unique() if p.startswith("RESIDENCE")]
    cuts = {"all": d, "public housing": d[d["prem_typ_desc"] == "RESIDENCE - PUBLIC HOUSING"], "outside public housing": d[d["prem_typ_desc"] != "RESIDENCE - PUBLIC HOUSING"],
            "any residence": d[d["prem_typ_desc"].isin(residences)], "outside residences": d[~d["prem_typ_desc"].isin(residences)],
            "homeless shelter": d[d["prem_typ_desc"] == "HOMELESS SHELTER"], "street": d[d["prem_typ_desc"] == "STREET"],
            "recorded by NYPD precincts": d[d["juris_desc"] == "N.Y. POLICE DEPT"], "recorded by Housing police": d[d["juris_desc"] == "N.Y. HOUSING POLICE"],
            "recorded by Transit police": d[d["juris_desc"] == "N.Y. TRANSIT POLICE"]}
    out = {}
    for k, x in cuts.items():
        n = x.groupby("g")["n"].sum()
        rate = {g: n.get(g, 0) / popF[g] / YEARS * 1e5 for g in ("Black", "White", "Hispanic")}
        out[k] = {"black_rate": round(rate["Black"]), "white_rate": round(rate["White"]), "ratio_white": round(rate["Black"] / rate["White"], 2) if rate["White"] else None,
                  "ratio_hispanic": round(rate["Black"] / rate["Hispanic"], 2) if rate["Hispanic"] else None,
                  "share_black_women_pct": round(n.get("Black", 0) / tot["Black"] * 100, 1), "share_white_women_pct": round(n.get("White", 0) / tot["White"] * 100, 1)}
    (ROOT / "out/nyc_premises.json").write_text(json.dumps(out, indent=1) + "\n")
    L = ["# New York: Black women's recorded assault rate against White women's, by place and recording agency, 2022 to 2025", "",
         "Women of all ages, per 100,000 women residents of the group a year. Generated by `scripts/nyc_premises.py`.", "",
         "| Cut | Black women | White women | Ratio vs White | Ratio vs Hispanic | Share of Black women's assaults | Share of White women's |", "|---|---|---|---|---|---|---|"]
    for k, r in out.items():
        L.append(f"| {k} | {r['black_rate']:,} | {r['white_rate']:,} | {r['ratio_white']} | {r['ratio_hispanic']} | {r['share_black_women_pct']}% | {r['share_white_women_pct']}% |")
    (ROOT / "out/nyc_premises.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
